import {VECTOR_LEVEL} from './vector-world.js';
import {PERMUTATION_LEVEL} from './permutation-world.js';
import {WRAP_LEVEL} from './wrap-world.js';
import {ARITHMETIC_LEVELS} from './arithmetic-worlds.js';
import {LEVELS_BASE} from './mirror-composition-worlds.js';
import {PAIRED_LEVEL} from './expansion-worlds.js';
import {AE_LEVEL} from './ae-world.js';
import {DERIVATIVE_LEVEL} from './derivative-world.js';
// Independently testable game mechanisms. Mathematical claims are deliberately local and explicit.
export const LEVELS = [
 {id:1,name:['归纳桥','One Step Implies the Next'],tag:['显然，还差一步。','Clearly. Except for the bridge.'],color:0xdce8de,ink:0x315b53,accent:0xc19a50,ground:0xeae8d6,kind:'induction',width:60,completion:['主桥一块接一块，脚注也能通向下一页。','The main bridge grows step by step. Footnotes also lead onward.'],
 hint:['← → 走；↑ 起跳；空中再按 ↑ 振翅。落脚就能恢复。','← → move · ↑ jump · tap ↑ again in air to flap. Land to recharge.'],
 task:['真正踩上这一块，下一块才成立。','Land on a real step to establish the next.'],
 jokes:[['显然：前方有桥。小鸟：桥呢？','The proof says “clearly.” The bridge says nothing.'],['不是你没看懂。是真的少了一步。','You did not miss the step. The author did.'],['证明留作练习。练习现在长腿了。','Proof left as an exercise. The exercise has legs.']],
 proof:["设 \\(P(n)\\) 表示“第 \\(n\\) 块踏板已经建立”。先建立 \\(P(0)\\)，再按 \\(P(n)\\Rightarrow P(n+1)\\) 逐块延伸，所以每个有限编号的踏板都能建立。\n游戏中的桥只有有限块；虚线仅是待建立的踏板，不能当作已经成立的命题。", "Let \\(P(n)\\) mean that step \\(n\\) has been established. Establish \\(P(0)\\), then use \\(P(n)\\Rightarrow P(n+1)\\) to extend the bridge. Every finite-index step is eventually established.\nThis bridge is finite. An outlined step is a preview, not an established statement."],
 boundary:['归纳逻辑只对应逐块建立的主桥；支路与追逐是玩法，抓到配角不等于证明命题。','The induction logic concerns the main bridge. Side routes and the chase are gameplay; catching a character does not prove a theorem.']},
 {id:2,name:['你俩商量好了吗？','Same Place, Same Time'],tag:['各走各的，终于碰头。','Different periods. Finally in sync.'],color:0xe4e8dc,ink:0x416354,accent:0xc0954c,ground:0xeae2c9,kind:'period',width:80,
 hint:['两组平台按 4 秒、6 秒绕行；每 12 秒一起回到原位。','The platforms return every 4 s and 6 s. Their common return is every 12 s.'],task:['等两组轨道同时回到起点，穿过合拍门。','Pass the gate when both orbit markers return to their start.'],jokes:[['它们没有拖延，只是周期不同。','Not procrastinating. Operating on different periods.'],['约到了。不是因为群聊里有人回了“都行”。','A meeting time, without a 47-message group chat.'],['最小公倍数，最大社交善意。','LCM: the calendar app mathematics deserved.']],
 proof:["两机关的周期分别为 4 秒和 6 秒，且在 \\(t=0\\) 同时处于原位。它们共同回到原位的时刻是 12 的非负整数倍。\n为了可玩，门在共同返回后短暂开启；这个宽容窗口是游戏规则。", "Two mechanisms have periods 4 s and 6 s and start at their reference positions at \\(t=0\\). Their common return times are the nonnegative multiples of 12.\nThe short opening after a common return is a gameplay tolerance."],
 boundary:['有限周期模型；不宣称混合性，也不把有限观察当成无理转动的证明。','A finite periodic model. No mixing claim and no inference about irrational rotations.']},
 {id:3,name:['反着走的时间','An Inverse, Not a Rewind'],tag:['鸟照常走，机关反着转。','Same bird. Opposite phase.'],color:0xd6e2e4,ink:0x3e6273,accent:0xa792b3,ground:0xe7e5db,kind:'inverse',width:78,
 hint:['进入紫色区域，平台相位倒转；走出区域，就恢复正向。','Inside the violet field, platform phase runs backward. Outside, forward.'],task:['用反向区把升降台送到脚下。','Use the inverse field to bring the lift to your feet.'],jokes:[['撤回一句“显然”，不等于撤回整个人生。','Undo “obvious.” Your life remains untouched.'],['方向反了，交稿日可没往回走。','Time reversed. The deadline did not.'],['机关倒回去了，刚才那一跤不行。','The platform went back. Your last fall did not.']],
 proof:["圆周相位的正向与反向映射满足\n\\[\\begin{aligned}T(\\theta)&=\\theta+\\alpha\\pmod 1,\\\\T^{-1}(\\theta)&=\\theta-\\alpha\\pmod 1,\\\\T^{-1}\\circ T&=\\mathrm{id}.\\end{aligned}\\]\n机关正转相位量 \\(\\alpha\\)，再反转同样的量，就回到同一个机关状态。", "Forward and inverse translations of circle phase satisfy\n\\[\\begin{aligned}T(\\theta)&=\\theta+\\alpha\\pmod 1,\\\\T^{-1}(\\theta)&=\\theta-\\alpha\\pmod 1,\\\\T^{-1}\\circ T&=\\mathrm{id}.\\end{aligned}\\]\nMove the phase forward by \\(\\alpha\\), then backward by the same amount, and the mechanism returns to its state."],
 boundary:['只倒转可逆的机关相位。不会撤回收集品、碰撞或玩家的整段历史。','Only an invertible mechanism phase is reversed, not collisions, collectibles, or the whole game history.']},
 {id:4,name:['路有点记仇','The Path Remembers'],tag:['你刚才飞过哪里，路还记得。','Your last two choices built this path.'],color:0xe9e1df,ink:0x745a67,accent:0xc69978,ground:0xeee5db,kind:'symbols',width:82,
 hint:["在标志处，走上路记圆，下路记三角；最近两步造下一段路。", "At each marker: high lane ○, low lane △. Your last two choices build the next path."],task:["下一个符号进来，最早那个就离开；已经走过的那段路会留下。", "A new symbol arrives and the oldest leaves. Earlier path sections remain in place."],jokes:[['不是玄学，是一个两位内存。','Not destiny. A two-symbol memory.'],['你以为翻篇了，路还截着图。','You moved on. The path kept receipts.'],['系统只记两步。比我强。','The system remembers two steps. An aspirational amount.']],
 proof:["字母表为 \\(\\{\\circ,\\triangle\\}\\)，状态只保存最近两项。读入新符号 \\(c\\) 后，状态 \\(ab\\) 更新为 \\(bc\\)。\n共有四种两符号状态。造路的门用当时的状态选出下一段地形，每种状态都有通路；后一个门不会删除先前那段路。", "The alphabet is \\(\\{\\circ,\\triangle\\}\\). The state stores only the last two symbols: reading \\(c\\) updates \\(ab\\) to \\(bc\\).\nThere are four two-symbol states. A path-building gate uses its current state to select the next terrain section, and every state has a route. A later gate does not delete earlier sections."],
 boundary:['这是有限状态移位规则的玩具模型；不由四个状态推断熵或复杂系统性质。','A finite-state shift rule, not a computation of entropy or a claim about a complex system.']},
 {id:5,name:['几乎有桥','Almost a Bridge'],tag:['“几乎”两个字，鸟不同意。','The bird objects to “almost.”'],color:0xd8e8e7,ink:0x326e69,accent:0xbcad61,ground:0xe8e8d6,kind:'cover',width:72,
 hint:["这一关，再按 ↑ 振翅时，也会在脚下落一段墨桥；落地补充。", "In this world, your second ↑ both flaps and paints a bridge below. Land to recharge."],task:["把墨带一段段接起来。标记之间没有缝，门就开。", "Join the ink strokes. Cover the marked gap completely to open the gate."],jokes:[['覆盖了 99%。剩下 1% 正好在你脚下。','99% covered. You found the other 1%.'],['“端点不重要。”端点本人提出异议。','“Endpoints do not matter.” The endpoint has concerns.'],['并集成功。小鸟暂不接受空集。','Union successful. The bird declines the empty set.']],
 proof:["每次振翅落墨的中心是 \\(c_j\\)，对应闭区间 \\(I_j=[c_j-4,c_j+4]\\)。将中心排序后，若相邻中心差不超过 8，则这些区间相接，构成一个闭区间。\n若并集同时包含标记的左右端点 12 和 48，便覆盖整段 \\([12,48]\\)。游戏逐次检查真实留下的有限条墨带，缺口未补齐时出口不打开。", "An ink stroke centered at \\(c_j\\) creates the closed interval \\(I_j=[c_j-4,c_j+4]\\). After sorting the centers, consecutive gaps of at most 8 make the union one connected closed interval.\nIf that union contains the marked endpoints 12 and 48, it covers \\([12,48]\\). The game checks the finite collection actually painted; an uncovered gap keeps the gate closed."],
 boundary:["这是有限闭区间覆盖；数值比较只用极小浮点容差。并非紧致性定理，也不是飞过去就自动证明覆盖。", "This is a finite closed-interval cover with a tiny floating-point tolerance. Flying across is not itself proof of coverage, and no compactness theorem is claimed."]},
 {id:6,name:['到底什么时候','Eventually. But When?'],tag:['每一段都说快了，快得不一样。','Every platform says “soon.” Differently.'],color:0xdde2ee,ink:0x515f80,accent:0xc29f62,ground:0xe8e6e1,kind:'threshold',width:80,
 hint:['穿过起点线，三段分别在 2、5、8 秒后永久稳定。','Cross the start line. Three sections stabilize permanently after 2, 5, and 8 seconds.'],task:['找安全台等一等。8 秒之后，三段同时稳定。','Wait on a safe perch. After 8 seconds all three sections stay stable.'],jokes:[['“马上”是三个不同的实数。','“Soon” turned out to be three different numbers.'],['三个“马上”，最晚那个说了算。','Three versions of “soon.” The last one sets the schedule.'],['统一了。导师的“很快”不在定义域里。','Uniform at last. Your supervisor’s “soon” is outside the domain.']],
 proof:["有限三段的稳定阈值为 \\(N_1=2\\)、\\(N_2=5\\)、\\(N_3=8\\)。取 \\(N=\\max(N_1,N_2,N_3)=8\\)，则 \\(t\\ge N\\) 时三段都已稳定。\n“稳定”在本关表示此后不再消失，不是周期性地暂时亮起。", "The three stabilization thresholds are \\(N_1=2\\), \\(N_2=5\\), and \\(N_3=8\\). Taking \\(N=\\max(N_1,N_2,N_3)=8\\) ensures every section is stable for \\(t\\ge N\\).\nHere “stable” means permanently present thereafter, not periodically flashing on."],
 boundary:['关键是有限个阈值。无限族的阈值可能无界，不能直接套用这个最大值。','Finiteness matters. An infinite family of thresholds may be unbounded.']},
 {id:7,name:['我过去了，我影子呢？','Did My Shadow Make It?'],tag:['上面过了，下面也得过。','Both tracks. Same input.'],color:0xd5e0e6,ink:0x405e76,accent:0xc6a76e,ground:0xe3e5df,kind:'shadow',width:80,
 hint:['影子与你同步。跳跃要同时避开上下两条轨道的障碍。','Your shadow follows the same jump. Avoid obstacles on both tracks.'],task:['两条轨道都安全，才是真的安全。','Safe means safe on both tracks.'],jokes:[['一份输入，双倍审稿意见。','One input. Twice the referee reports.'],['本体没问题。合作者那边有一点小问题。','Your part is fine. Your coauthor has one small issue.'],['“以及”比“或者”累多了。','“And” does considerably more work than “or.”']],
 proof:["将上轨安全位置记为 \\(A\\)，下轨允许位置经平移换到同一坐标后记为 \\(B\\)。两者必须同时安全，所以共同允许的位置为 \\(A\\cap B\\)。\n下轨影子只是上轨小鸟的平移副本，接收同一输入。", "Let \\(A\\) be upper-track safe states, and translate lower-track safe states into the same coordinates to obtain \\(B\\). Both must be safe, so the allowed set is \\(A\\cap B\\).\nThe shadow is a translated copy driven by the same input."],
 boundary:['这是共享输入下约束取交集的有限机关，不是对任意乘积系统作遍历性断言。','A finite shared-input intersection of constraints, not an ergodicity claim about arbitrary product systems.']},
 {id:8,name:['换个尺度再证明','A Change of Scale'],tag:['小一点钻进去，大一点想清楚。','Think small. Land the big idea.'],color:0x233f4c,ink:0xbee1ce,accent:0xd6bb77,ground:0xd6d7c5,kind:'scale',width:91,
 hint:['金色透镜改变大小。缩小穿洞，恢复后跃上高台。','Golden lenses change your scale. Shrink through the tunnel, then grow for the high ledge.'],task:['最后两份折页，碰一碰就展开。里面还会有一页。','Nudge the two folded notes at the end. Another page is waiting inside.'],jokes:[['换了尺度，问题还在。现在至少钻得过去。','A new scale. Same problem. Better clearance.'],['不是把难题缩小，是把鸟缩小。','The problem is not smaller. You are.'],['证毕：折腾归折腾，这一步总算成立。','Q.E.D.: Quite Enough Drama.']],
 proof:["以鸟脚为局部坐标原点，缩放 \\(S_s(u,v)=(su,sv)\\)，其中 \\(s>0\\)。其逆为 \\(S_{1/s}\\)，所以恢复原比例可把尺寸还原。碰撞宽高也按同一比例 \\(s\\) 改变。\n为保持操作手感，水平速度上限、起跳速度和振翅速度按 \\(\\sqrt{s}\\) 缩放；重力、横向加速度和制动参数保持原设定。洞和台阶保持原样，因此不同大小会有不同的通路。", "Using the feet as the local origin, the scaling is \\(S_s(u,v)=(su,sv)\\), with \\(s>0\\). Its inverse is \\(S_{1/s}\\), so restoring the ratio restores the dimensions. Collision width and height use the same factor \\(s\\).\nFor the control feel, the horizontal speed cap and the jump/flap speeds scale by \\(\\sqrt{s}\\). Gravity, horizontal acceleration and braking parameters keep their original settings. The tunnel and ledges stay in place, so different sizes allow different routes."],
 boundary:['这里的数学是可逆缩放及其使用边界。末尾展开折页是游戏小剧场，不是完成数学证明。','The mathematics concerns invertible scaling and its limits. Unfolding the final notes is a playful epilogue, not a mathematical proof.']}
,
{"id": 9, "name": ["后面还有一点", "There Is Always a Tail"], "tag": ["桥伸出去了，尾巴还在后面。", "The bridge moved. The tail is still coming."], "color": 15066584, "ink": 5072981, "accent": 12099676, "ground": 15328722, "kind": "series", "width": 65, "hint": ["↑ 顶正项包让桥前进，顶负项包让桥收回；两边剩下的范围都进槽，门才开。", "Bump positive packets to extend the bridge and negative packets to retract it. The whole remaining range must fit the dock."], "task": ["自己决定取包顺序。下层小路可以随时回去补另一边。", "Choose the packet order. The lower path lets you return to either supply rail."], "jokes": [["刚好够长，和后面不会变长，是两回事。", "Long enough now is not the same as finished."], ["这回连没拿来的那些，也给留了位置。", "Room reserved, including the terms still in transit."], ["桥说够了。尾巴说再等等。", "The bridge says done. The tail would like a word."]], "proof": ["正项依次为 \\(1,1/4,1/16,\\ldots\\)，负项依次为 \\(-1/2,-1/8,-1/32,\\ldots\\)。这是绝对收敛的几何级数，总和为 \\(2/3\\)。\n取过 \\(p\\) 个正项和 \\(q\\) 个负项后，真实部分和为 \\(S\\)，未取正项总和为 \\(P=\\frac43 4^{-p}\\)，未取负项绝对值之和为 \\(N=\\frac23 4^{-q}\\)。后续任一有限取法的部分和以及最终和都位于 \\([S-N,S+P]\\)。\n游戏要求整个区间落入 \\([0.64,0.69]\\)。两边各取三包即可做到；不是声称已经执行了无穷多步。", "The positive rail supplies \\(1,1/4,1/16,\\ldots\\); the negative rail supplies \\(-1/2,-1/8,-1/32,\\ldots\\). The series is absolutely convergent and its sum is \\(2/3\\).\nAfter taking \\(p\\) positive and \\(q\\) negative terms, let the actual partial sum be \\(S\\). The remaining positive total is \\(P=\\frac43 4^{-p}\\), and the magnitude of the remaining negative total is \\(N=\\frac23 4^{-q}\\). Every later finite partial sum, as well as the limit, lies in \\([S-N,S+P]\\).\nThe game checks that this whole interval lies in \\([0.64,0.69]\\). Three packets from each rail suffice. No infinite sequence of physical actions is claimed."], "boundary": ["桥头运输动画只是两个部分和状态间的过渡。尾项界来自明确的几何级数公式；不同取法不改变极限，是因为这里绝对收敛，不能推广到任意条件收敛级数。", "The transport animation interpolates between partial-sum states. Tail bounds come from the explicit geometric formulas. Order does not change this limit because the series is absolutely convergent; that claim does not extend to every conditionally convergent series."]},
{"id": 10, "name": ["刚才流过去多少？", "Every Drop Counts"], "tag": ["刚才多站那会儿，也算数。", "That extra second counted."], "color": 14477543, "ink": 3762535, "accent": 12494693, "ground": 15330008, "kind": "integral", "width": 91, "hint": ["站在加号踏板上进水，减号踏板上出水；离开就停。把水面调到金线，再起跳。", "Stand on plus to fill and minus to drain. Step off to stop. Bring the water to the gold line, then jump."], "task": ["水位记录的是实际流过的总量，不是最后踩了哪一块。", "The water keeps the signed total, not merely the last pad you touched."], "jokes": [["脚松开了，刚才那段时间可没撤回。", "You stepped off. The last few seconds still count."], ["正的负的，都算清了再上船。", "Credits, debits, and one remarkably buoyant bird."], ["多站一会儿，真的会多一点。", "It is not a metaphor. Staying longer adds more."]], "proof": ["踏板控制分段常数的实际流量 \\(q(t)\\)。在一段持续时间 \\(\\Delta t\\) 内，体积变化为 \\(q\\Delta t\\)。因此\n\\[V(t)=V(0)+\\int_0^t q(s)\\,ds=V(0)+\\sum_j q_j\\Delta t_j.\\]\n水箱截面积固定为 \\(A=2\\)，水面高度为 \\(h=-1+V/A\\)。进水计正，出水计负；离开踏板后流量为零，已经积累的体积保留。", "The pads control a piecewise constant actual flow \\(q(t)\\). A constant flow over time \\(\\Delta t\\) changes volume by \\(q\\Delta t\\), so\n\\[V(t)=V(0)+\\int_0^t q(s)\\,ds=V(0)+\\sum_j q_j\\Delta t_j.\\]\nThe tank has constant cross-sectional area \\(A=2\\), giving water height \\(h=-1+V/A\\). Filling is positive and draining negative. Leaving a pad sets flow to zero while retaining the accumulated volume."], "boundary": ["本关流量确实分段常数，按每段流量乘持续时间累计。空箱或满箱会停止实际流量，不把越界后偷偷截断的水位冒充同一个积分。计算只受普通浮点误差影响；停靠绿带是操作宽容度。", "Flow is piecewise constant and accumulated as rate times duration. An empty or full tank stops actual flow; the game does not silently clamp a continuing integral. Only ordinary floating-point error remains. The docking band is a gameplay tolerance."]}
,
DERIVATIVE_LEVEL
,
AE_LEVEL
,
PAIRED_LEVEL
,
...LEVELS_BASE
,
...ARITHMETIC_LEVELS,
WRAP_LEVEL,
PERMUTATION_LEVEL,
VECTOR_LEVEL
];
