
'use strict';
const $=id=>document.getElementById(id);let r=3,model='standard',chartTimer=null,tourTimer=null,tourIndex=0,selectedEnd=null;
const gcd=(a,b)=>b?gcd(b,a%b):a;
function countsFor(r,model='standard'){let counts=[1,0,0,0];const steps=model==='even'?[0,2]:model==='odd'?[1,3]:[0,1];for(let n=0;n<r;n++){const next=[0,0,0,0];for(let j=0;j<4;j++)for(const s of steps)next[(j+s)%4]+=counts[j];counts=next;}return counts;}
function frac(a,b){if(!a)return '0';const d=gcd(a,b);return b/d===1?String(a/d):`${a/d}/${b/d}`;}
function pct(p){return `${Number((p*100).toFixed(3))}%`;}
function stopChart(){clearInterval(chartTimer);chartTimer=null;$('play').textContent='Play';$('play').setAttribute('aria-pressed','false');}
function stopTour(){clearInterval(tourTimer);tourTimer=null;$('tour-play').textContent='Play the tour';$('tour-play').setAttribute('aria-pressed','false');}
function texFrac(a,b){if(!a)return '0';const d=gcd(a,b);return b/d===1?String(a/d):String.raw`\frac{${a/d}}{${b/d}}`;}
function mathText(id,text){if(globalThis.MathNotes)globalThis.MathNotes.setText($(id),text);else $(id).textContent=text;}
function render(){const counts=countsFor(r,model),den=2**r,ps=counts.map(n=>n/den);$('r-value').textContent=r;$('r-slider').value=r;$('back').disabled=r===1;$('next').disabled=r===12;
ps.forEach((p,j)=>{const bar=$(`bar${j}`);bar.style.height=`${p*200}%`;bar.classList.toggle('zero',p===0);bar.classList.toggle('selected',selectedEnd===j);$(`percent${j}`).textContent=pct(p);mathText(`fraction${j}`,String.raw`\(${texFrac(counts[j],den)}\)`);$(`node-p${j}`).textContent=pct(p);bar.setAttribute('aria-label',`Residue ${j} has probability ${frac(counts[j],den)}, or ${pct(p)}`);});
const distribution=`(${counts.map(c=>frac(c,den)).join(', ')})`,texDistribution=String.raw`\left(${counts.map(c=>texFrac(c,den)).join(',\,')}\right)`;let explanation=model==='even'?'It stays on even residues and does not approach uniformity on all four positions.':model==='odd'?`Only ${r%2?'odd':'even'} positions occur; parity alternates with the addition count.`:r<3?'Not all positions are reached, and the law is not uniform.':r===3?String.raw`All four positions have positive probability, but they are not all \(\frac14\). `:'It is closer to uniformity, but still not exactly uniform.';
mathText('distribution-line',String.raw`\(r=${r}\): \(${texDistribution}\). ${explanation}`);const tv=ps.reduce((s,p)=>s+Math.abs(p-.25),0)/2;mathText('tv-line',String.raw`Distance from uniformity (total variation): \(${texFrac(Math.round(tv*den*4),den*4)}\approx${Number(tv.toFixed(6))}\) . Only \(0\) means the laws agree exactly.`);
const title=model==='standard'?'Original model: add zero or one':model==='even'?'Even model: add zero or two':'Odd model: add one or three';$('cycle-title').textContent=title;$('cycle-desc').textContent=`${title}. After ${r} additions, residues 0, 1, 2, 3 have probabilities ${distribution}. The arrows show only the order of the residues.`;
const labels=document.querySelectorAll('.cycle-label');labels[0].textContent=model==='standard'?'Add 1: one step':model==='even'?'Add 2: opposite':'Add 1 or 3: flip parity';labels[1].textContent=model==='odd'?'Parity alternates':'Add 0: stay';
mathText('fourier-current',String.raw`Original model's nonzero frequency magnitude: \[\begin{aligned}|\lambda|^{${r}}&=2^{-\frac{${r}}2}\\&\approx${Math.pow(2,-r/2).toFixed(6)}>0.\end{aligned}\]`);return {counts,den,ps,tv};}
function changeR(value){stopChart();stopTour();r=Math.max(1,Math.min(12,Number(value)));selectedEnd=null;render();}
document.querySelectorAll('[data-prediction]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-prediction]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));const responses={yes:'The exact probabilities are \\(\\left(\\frac18,\\frac38,\\frac38,\\frac18\\right)\\). Every position is reached, but with unequal probabilities. The calculation below explains why.',no:'The calculation gives \\(\\left(\\frac18,\\frac38,\\frac38,\\frac18\\right)\\). The steps below explain the difference.',unsure:'Keep the question open: eight equally likely paths give \\(\\left(\\frac18,\\frac38,\\frac38,\\frac18\\right)\\). Compare the paths with the chart below.'};mathText('prediction-result',responses[btn.dataset.prediction]);$('prediction-result').hidden=false;$('lesson').hidden=false;render();}));
function setPath(expert){$('popular-path').setAttribute('aria-pressed',String(!expert));$('expert-path').setAttribute('aria-pressed',String(expert));document.querySelectorAll('.expert').forEach(d=>{if(d.closest('#method'))return;d.open=expert;});$('path-note').textContent=expert?'Definitions, finite proofs, Fourier multipliers, and limit conditions are expanded alongside the same diagrams.':'Begin by counting outcomes; definitions and proofs can be expanded at any time.';}
$('skip-prediction').addEventListener('click',()=>{$('lesson').hidden=false;setPath(true);render();});
$('popular-path').addEventListener('click',()=>setPath(false));$('expert-path').addEventListener('click',()=>setPath(true));
document.querySelectorAll('.pair').forEach(btn=>btn.addEventListener('click',()=>{stopChart();stopTour();document.querySelectorAll('.pair').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));const a=Number(btn.dataset.a),b=Number(btn.dataset.b),end=(a+b)%4;model='standard';$('model-select').value=model;r=2;selectedEnd=end;mathText('pair-feedback',String.raw`\(${a}+${b}=${end}\), and this path contributes \(\frac14\). `+(end===1?String.raw`Another path reaches 1, so the two contribute \(\frac12\). `:String.raw`Only one path reaches this position, with total probability \(\frac14\). `)+'The chart now shows two additions and highlights this endpoint.');render();}));
$('back').addEventListener('click',()=>changeR(r-1));$('next').addEventListener('click',()=>changeR(r+1));$('r-slider').addEventListener('input',e=>changeR(e.target.value));$('reset-chart').addEventListener('click',()=>changeR(1));$('play').addEventListener('click',()=>{if(chartTimer){stopChart();return;}stopTour();selectedEnd=null;if(r===12)r=1;render();$('play').textContent='Pause';$('play').setAttribute('aria-pressed','true');chartTimer=setInterval(()=>{r++;render();if(r>=12)stopChart();},1600);});
const tourText=Array.from(document.querySelectorAll('#transcript li')).map(li=>li.getAttribute('data-transcript')||li.textContent);
function renderTour(){mathText('tour-frame',tourText[tourIndex]);$('tour-progress').textContent=`${tourIndex+1} / ${tourText.length}`;$('tour-prev').disabled=tourIndex===0;$('tour-next').disabled=tourIndex===tourText.length-1;document.querySelectorAll('#transcript li').forEach((li,i)=>li.classList.toggle('active',i===tourIndex));}
$('tour-prev').addEventListener('click',()=>{stopTour();tourIndex=Math.max(0,tourIndex-1);renderTour();});$('tour-next').addEventListener('click',()=>{stopTour();tourIndex=Math.min(tourText.length-1,tourIndex+1);renderTour();});$('tour-reset').addEventListener('click',()=>{stopTour();tourIndex=0;renderTour();});$('tour-play').addEventListener('click',()=>{if(tourTimer){stopTour();return;}stopChart();if(tourIndex===tourText.length-1)tourIndex=0;renderTour();$('tour-play').textContent='Pause the tour';$('tour-play').setAttribute('aria-pressed','true');tourTimer=setInterval(()=>{tourIndex++;renderTour();if(tourIndex===tourText.length-1)stopTour();},6500);});
document.querySelectorAll('[data-transfer]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-transfer]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));const lead=btn.dataset.transfer==='even'?'Yes. Even plus even remains even.':btn.dataset.transfer==='uniform'?'This rule does not approach uniformity on all four positions.':'Consider parity: even plus even remains even.';mathText('transfer-result',String.raw`${lead} For every \(r\ge1\) the law is \(\left(\frac12,0,\frac12,0\right)\). More additions cannot leave \(\{0,2\}\). Change the rule to compare the same chart.`);$('transfer-result').hidden=false;$('model-control').hidden=false;}));
$('model-select').addEventListener('change',e=>{stopChart();stopTour();model=e.target.value;selectedEnd=null;render();$('model-note').textContent=model==='standard'?'The original model approaches uniformity but is never exactly uniform at a finite step.':model==='even'?'Odd positions always have probability zero, however many additions are made.':'The support generates the whole group, but alternating parity creates periodicity. Compare consecutive steps.';});
$('reset-all').addEventListener('click',()=>{stopChart();stopTour();if($('lesson-video')){$('lesson-video').pause();$('lesson-video').currentTime=0;}r=3;model='standard';tourIndex=0;selectedEnd=null;$('lesson').hidden=true;$('prediction-result').hidden=true;$('prediction-result').textContent='';$('transfer-result').hidden=true;$('model-control').hidden=true;$('model-select').value='standard';$('teachback').value='';$('model-note').textContent='Changing the rule keeps the current addition count.';document.querySelectorAll('[data-prediction],[data-transfer],.pair').forEach(b=>b.setAttribute('aria-pressed','false'));mathText('pair-feedback',String.raw`Order matters: \(0+1\) and \(1+0\) are different sequences of choices.`);setPath(false);render();renderTour();document.querySelector('[data-prediction]').focus();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopChart();stopTour();}});render();renderTour();
