
'use strict';
const $=id=>document.getElementById(id);let r=3,model='standard',chartTimer=null,tourTimer=null,tourIndex=0,selectedEnd=null;
const gcd=(a,b)=>b?gcd(b,a%b):a;
function countsFor(r,model='standard'){let counts=[1,0,0,0];const steps=model==='even'?[0,2]:model==='odd'?[1,3]:[0,1];for(let n=0;n<r;n++){const next=[0,0,0,0];for(let j=0;j<4;j++)for(const s of steps)next[(j+s)%4]+=counts[j];counts=next;}return counts;}
function frac(a,b){if(!a)return '0';const d=gcd(a,b);return b/d===1?String(a/d):`${a/d}/${b/d}`;}
function pct(p){return `${Number((p*100).toFixed(3))}%`;}
function stopChart(){clearInterval(chartTimer);chartTimer=null;$('play').textContent='播放变化';$('play').setAttribute('aria-pressed','false');}
function stopTour(){clearInterval(tourTimer);tourTimer=null;$('tour-play').textContent='播放导览';$('tour-play').setAttribute('aria-pressed','false');}
function texFrac(a,b){if(!a)return '0';const d=gcd(a,b);return b/d===1?String(a/d):String.raw`\frac{${a/d}}{${b/d}}`;}
function mathText(id,text){if(globalThis.MathNotes)globalThis.MathNotes.setText($(id),text);else $(id).textContent=text;}
function render(){const counts=countsFor(r,model),den=2**r,ps=counts.map(n=>n/den);$('r-value').textContent=r;$('r-slider').value=r;$('back').disabled=r===1;$('next').disabled=r===12;
ps.forEach((p,j)=>{const bar=$(`bar${j}`);bar.style.height=`${p*200}%`;bar.classList.toggle('zero',p===0);bar.classList.toggle('selected',selectedEnd===j);$(`percent${j}`).textContent=pct(p);mathText(`fraction${j}`,String.raw`\(${texFrac(counts[j],den)}\)`);$(`node-p${j}`).textContent=pct(p);bar.setAttribute('aria-label',`余数 ${j} 的概率为 ${frac(counts[j],den)}，即 ${pct(p)}`);});
const distribution=`(${counts.map(c=>frac(c,den)).join(', ')})`,texDistribution=String.raw`\left(${counts.map(c=>texFrac(c,den)).join(',\,')}\right)`;let explanation=model==='even'?'始终只在偶数位置，不会趋于整个四点集合上的均匀分布。':model==='odd'?`当前只在${r%2?'奇数':'偶数'}位置；奇偶性随次数交替。`:r<3?'尚未覆盖全部位置，也不均匀。':r===3?String.raw`四个位置都有正概率，但不是四个 \(\frac14\)。`:'越来越接近均匀，但此刻仍不精确均匀。';
mathText('distribution-line',String.raw`\(r=${r}\)：\(${texDistribution}\)。${explanation}`);const tv=ps.reduce((s,p)=>s+Math.abs(p-.25),0)/2;mathText('tv-line',String.raw`与均匀的差距（总变差距离）：\(${texFrac(Math.round(tv*den*4),den*4)}\approx${Number(tv.toFixed(6))}\)。等于 \(0\) 才表示完全相同。`);
const title=model==='standard'?'原模型：每次加零或一':model==='even'?'偶数模型：每次加零或二':'奇数模型：每次加一或三';$('cycle-title').textContent=title;$('cycle-desc').textContent=`${title}。相加${r}次后，余数0、1、2、3的概率分别为${distribution}。圆环上的箭头仅标示余数的排列方向。`;
const labels=document.querySelectorAll('.cycle-label');labels[0].textContent=model==='standard'?'加一：顺时针一格':model==='even'?'加二：跳到对面':'加一或三：改变奇偶';labels[1].textContent=model==='odd'?'奇、偶位置交替':'加零：留在原地';
mathText('fourier-current',String.raw`原模型的非零频率幅度：\[\begin{aligned}|\lambda|^{${r}}&=2^{-\frac{${r}}2}\\&\approx${Math.pow(2,-r/2).toFixed(6)}>0.\end{aligned}\]`);return {counts,den,ps,tv};}
function changeR(value){stopChart();stopTour();r=Math.max(1,Math.min(12,Number(value)));selectedEnd=null;render();}
document.querySelectorAll('[data-prediction]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-prediction]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));const responses={yes:'这个直觉值得检验：实际概率是 \\(\\left(\\frac18,\\frac38,\\frac38,\\frac18\\right)\\)。四个位置都能到，但机会不一样。下面逐步核对。',no:'计算结果是 \\(\\left(\\frac18,\\frac38,\\frac38,\\frac18\\right)\\)。接着看这个差异从哪里来。',unsure:'先把问题保留。八条等可能路径给出 \\(\\left(\\frac18,\\frac38,\\frac38,\\frac18\\right)\\)。下面用路径和图一起核对。'};mathText('prediction-result',responses[btn.dataset.prediction]);$('prediction-result').hidden=false;$('lesson').hidden=false;render();}));
function setPath(expert){$('popular-path').setAttribute('aria-pressed',String(!expert));$('expert-path').setAttribute('aria-pressed',String(expert));document.querySelectorAll('.expert').forEach(d=>{if(d.closest('#method'))return;d.open=expert;});$('path-note').textContent=expert?'定义、有限证明、Fourier 乘子与极限条件已展开；仍使用同一套图与对象。':'从数结果出发；严谨定义与证明可随时展开。';}
$('skip-prediction').addEventListener('click',()=>{$('lesson').hidden=false;setPath(true);render();});
$('popular-path').addEventListener('click',()=>setPath(false));$('expert-path').addEventListener('click',()=>setPath(true));
document.querySelectorAll('.pair').forEach(btn=>btn.addEventListener('click',()=>{stopChart();stopTour();document.querySelectorAll('.pair').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));const a=Number(btn.dataset.a),b=Number(btn.dataset.b),end=(a+b)%4;model='standard';$('model-select').value=model;r=2;selectedEnd=end;mathText('pair-feedback',String.raw`\(${a}+${b}=${end}\)，这条路径贡献 \(\frac14\)。`+(end===1?String.raw`位置 1 还有另一条路径，所以两条合计 \(\frac12\)。`:String.raw`这里只有一条路径，所以总概率是 \(\frac14\)。`)+'下方分布图已切到两次相加，并标出这个终点。');render();}));
$('back').addEventListener('click',()=>changeR(r-1));$('next').addEventListener('click',()=>changeR(r+1));$('r-slider').addEventListener('input',e=>changeR(e.target.value));$('reset-chart').addEventListener('click',()=>changeR(1));$('play').addEventListener('click',()=>{if(chartTimer){stopChart();return;}stopTour();selectedEnd=null;if(r===12)r=1;render();$('play').textContent='暂停变化';$('play').setAttribute('aria-pressed','true');chartTimer=setInterval(()=>{r++;render();if(r>=12)stopChart();},1600);});
const tourText=Array.from(document.querySelectorAll('#transcript li')).map(li=>li.getAttribute('data-transcript')||li.textContent);
function renderTour(){mathText('tour-frame',tourText[tourIndex]);$('tour-progress').textContent=`${tourIndex+1} / ${tourText.length}`;$('tour-prev').disabled=tourIndex===0;$('tour-next').disabled=tourIndex===tourText.length-1;document.querySelectorAll('#transcript li').forEach((li,i)=>li.classList.toggle('active',i===tourIndex));}
$('tour-prev').addEventListener('click',()=>{stopTour();tourIndex=Math.max(0,tourIndex-1);renderTour();});$('tour-next').addEventListener('click',()=>{stopTour();tourIndex=Math.min(tourText.length-1,tourIndex+1);renderTour();});$('tour-reset').addEventListener('click',()=>{stopTour();tourIndex=0;renderTour();});$('tour-play').addEventListener('click',()=>{if(tourTimer){stopTour();return;}stopChart();if(tourIndex===tourText.length-1)tourIndex=0;renderTour();$('tour-play').textContent='暂停导览';$('tour-play').setAttribute('aria-pressed','true');tourTimer=setInterval(()=>{tourIndex++;renderTour();if(tourIndex===tourText.length-1)stopTour();},6500);});
document.querySelectorAll('[data-transfer]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-transfer]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));const lead=btn.dataset.transfer==='even'?'对，偶数加偶数仍然是偶数。':btn.dataset.transfer==='uniform'?'这里不会趋于四个位置均匀。':'从奇偶性入手：偶数加偶数仍是偶数。';mathText('transfer-result',String.raw`${lead} 每个 \(r\ge1\) 都得到 \(\left(\frac12,0,\frac12,0\right)\)。相加次数再多，也跨不出 \(\{0,2\}\)。可以切换规则，继续对照同一张图。`);$('transfer-result').hidden=false;$('model-control').hidden=false;}));
$('model-select').addEventListener('change',e=>{stopChart();stopTour();model=e.target.value;selectedEnd=null;render();$('model-note').textContent=model==='standard'?'原模型趋于均匀，但有限次仍不精确均匀。':model==='even'?'即使增加相加次数，奇数位置的概率始终为零。':'支集能生成全群，但奇偶交替造成周期性；请比较相邻两次。';});
$('reset-all').addEventListener('click',()=>{stopChart();stopTour();if($('lesson-video')){$('lesson-video').pause();$('lesson-video').currentTime=0;}r=3;model='standard';tourIndex=0;selectedEnd=null;$('lesson').hidden=true;$('prediction-result').hidden=true;$('prediction-result').textContent='';$('transfer-result').hidden=true;$('model-control').hidden=true;$('model-select').value='standard';$('teachback').value='';$('model-note').textContent='切换后会保留当前相加次数。';document.querySelectorAll('[data-prediction],[data-transfer],.pair').forEach(b=>b.setAttribute('aria-pressed','false'));mathText('pair-feedback',String.raw`这里的顺序有意义：\(0+1\) 与 \(1+0\) 是两种不同的选择过程。`);setPath(false);render();renderTour();document.querySelector('[data-prediction]').focus();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopChart();stopTour();}});render();renderTour();
