'use strict';
function typewriterState(index,x){const k=Math.floor(Math.log2(index)),m=2**k,j=index-m,left=j/m,right=(j+1)/m;return {index,k,m,j,left,right,value:x>=left&&x<right?1:0,squareIntegral:1/m,norm:Math.sqrt(1/m)};}
const twGet=id=>document.getElementById(id);let twIndex=5,twX=.37,twTimer=null;
function twMath(id,text){const el=twGet(id);if(globalThis.MathNotes)globalThis.MathNotes.setText(el,text);else el.textContent=text;}
function twStop(){clearInterval(twTimer);twTimer=null;twGet('tw-play').textContent='Play';twGet('tw-play').setAttribute('aria-pressed','false');}
function twRender(){const s=typewriterState(twIndex,twX);twGet('tw-layer-display').textContent=s.k;twGet('tw-cell-display').textContent=`${s.j+1} / ${s.m}`;twGet('tw-layer').value=s.k;twGet('tw-x-label').textContent=twX.toFixed(3);twGet('tw-x').value=Math.round(twX*1000);twGet('tw-x').setAttribute('aria-valuetext',`x = ${twX.toFixed(3)}`);twGet('tw-active').setAttribute('x',28+s.left*744);twGet('tw-active').setAttribute('width',744/s.m);const mx=28+twX*744;twGet('tw-marker').setAttribute('x1',mx);twGet('tw-marker').setAttribute('x2',mx);twGet('tw-marker-dot').setAttribute('cx',mx);let grid='';for(let i=1;i<s.m;i++)grid+=`<line x1="${28+i/s.m*744}" x2="${28+i/s.m*744}" y1="35" y2="99"/>`;twGet('tw-grid').innerHTML=grid;
twMath('tw-interval',String.raw`\(\left[\frac{${s.j}}{${s.m}},\frac{${s.j+1}}{${s.m}}\right)\)`);twGet('tw-value').textContent=s.value;twMath('tw-hit-message',s.value?String.raw`\(x\) is inside the lit interval`:String.raw`\(x\) is outside the lit interval`);twMath('tw-square-integral',String.raw`\(\frac{1}{${s.m}}=${s.squareIntegral}\)`);twMath('tw-norm',String.raw`\(2^{-\frac{${s.k}}2}\approx${Number(s.norm.toFixed(6))}\)`);twMath('tw-status',String.raw`Currently \(n=${twIndex}\). Level ${s.k}, ${s.m} intervals; the fixed point lies in interval ${Math.floor(twX*s.m)+1} of this level. `+(twIndex===127?'The finite demonstration ends here; the mathematical sequence continues indefinitely.':'The demonstration covers levels 1–6.'));
twGet('tw-prev').disabled=twIndex===2;twGet('tw-next').disabled=twIndex===127;twGet('tw-desc').textContent=`The lit interval is [${s.left}, ${s.right}); the fixed point is ${twX}, where the function has value ${s.value}. The integral of the square is ${s.squareIntegral}, and the L2 norm is approximately ${s.norm.toFixed(6)}.`;return s;}
twGet('tw-prev').addEventListener('click',()=>{twStop();twIndex=Math.max(2,twIndex-1);twRender();});twGet('tw-next').addEventListener('click',()=>{twStop();twIndex=Math.min(127,twIndex+1);twRender();});twGet('tw-layer').addEventListener('change',e=>{twStop();twIndex=2**Number(e.target.value);twRender();});twGet('tw-x').addEventListener('input',e=>{twStop();twX=Math.max(0,Math.min(999,Number(e.target.value)))/1000;twRender();});twGet('tw-reset').addEventListener('click',()=>{twStop();twIndex=2;twX=.37;twRender();});twGet('tw-play').addEventListener('click',()=>{if(twTimer){twStop();return;}if(twIndex===127)twIndex=2;twRender();twGet('tw-play').textContent='Pause';twGet('tw-play').setAttribute('aria-pressed','true');twTimer=setInterval(()=>{twIndex++;twRender();if(twIndex>=127)twStop();},1100);});document.addEventListener('visibilitychange',()=>{if(document.hidden)twStop();});twRender();
